// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextAnalyzer.Infrastructure.Data;

#nullable disable

namespace TextAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(TextAnalyzerDbContext))]
    partial class TextAnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileEntitySessionEntity", b =>
                {
                    b.Property<Guid>("FilesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionsId")
                        .HasColumnType("uuid");

                    b.HasKey("FilesId", "SessionsId");

                    b.HasIndex("SessionsId");

                    b.ToTable("FileEntitySessionEntity");
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.ExecutionModeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExecutionModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModeName = "SingleFile"
                        },
                        new
                        {
                            Id = 2,
                            ModeName = "Folder"
                        });
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileHash")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.ResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<string>("LongestWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExecutionModeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionModeId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FileEntitySessionEntity", b =>
                {
                    b.HasOne("TextAnalyzer.Domain.Entities.FileEntity", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextAnalyzer.Domain.Entities.SessionEntity", null)
                        .WithMany()
                        .HasForeignKey("SessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.ResultEntity", b =>
                {
                    b.HasOne("TextAnalyzer.Domain.Entities.FileEntity", "File")
                        .WithOne("Result")
                        .HasForeignKey("TextAnalyzer.Domain.Entities.ResultEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.SessionEntity", b =>
                {
                    b.HasOne("TextAnalyzer.Domain.Entities.ExecutionModeEntity", "ExecutionMode")
                        .WithMany("Sessions")
                        .HasForeignKey("ExecutionModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionMode");
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.ExecutionModeEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TextAnalyzer.Domain.Entities.FileEntity", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
